# Alembic Configuration

sqlalchemy.url = postgresql+psycopg2://stronghold:stronghold_dev_password@localhost:5432/stronghold

script_location = alembic

sqlalchemy.echo = false
sqlalchemy.echo_pool = false

sqlalchemy.pool_recycle = 3600

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
